# Generated by Django 4.1 on 2022-09-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alpha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
    ]
